name: "Setup Environment"
description: "Sets up Java and checks out the repo"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Grant execute permissions to Maven Wrapper
      run: chmod +x mvnw
