name: Build and package task manager Quarkus app

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run Tests
        run: ./mvnw clean test

  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build JAR File
        run: ./mvnw package

      - name: Capture JAR file path
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Store JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-app
          path: ${{ env.JAR_FILE }}

      - name: Run Railway CLI inside Docker
        uses: docker://ghcr.io/railwayapp/cli:latest
        with:
          run: |
            railway login --token ${{ secrets.RAILWAY_TOKEN }}
            railway up --service=${{ secrets.RAILWAY_SERVICE_ID }} --artifact=${{ env.JAR_FILE }}