name: Build and package task manager Quarkus app

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run Tests
        run: ./mvnw clean test

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build JAR File
        run: ./mvnw package

      - name: Capture JAR file path
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Store JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-app
          path: ${{ env.JAR_FILE }}

  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      JAR_FILE: ${{ env.JAR_FILE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: |
          # Log in to Railway
          railway login --token $RAILWAY_TOKEN
          
          # Deploy the JAR file to Railway
          railway up --service=$SVC_ID --artifact=$JAR_FILE