name: Build and package task manager Quarkus app

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x mvnw

      - name: Run Tests
        run: ./mvnw clean test

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.1.1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x mvnw

      - name: Build JAR File
        run: ./mvnw package

      - name: Store JAR as Artifact
        uses: action/upload-artifact@v4
        with:
          name: quarkus-app
          path: target/*.jar